/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

/**
 *
 * @author josue
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNivelIntermedio = new javax.swing.JButton();
        btnNivelDificil = new javax.swing.JButton();
        btnNivelFacil = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNivelIntermedio.setBorderPainted(false);
        btnNivelIntermedio.setContentAreaFilled(false);
        btnNivelIntermedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivelIntermedioActionPerformed(evt);
            }
        });
        jPanel1.add(btnNivelIntermedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 220, 100));

        btnNivelDificil.setBorderPainted(false);
        btnNivelDificil.setContentAreaFilled(false);
        btnNivelDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivelDificilActionPerformed(evt);
            }
        });
        jPanel1.add(btnNivelDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, 210, 90));

        btnNivelFacil.setBorderPainted(false);
        btnNivelFacil.setContentAreaFilled(false);
        btnNivelFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivelFacilActionPerformed(evt);
            }
        });
        jPanel1.add(btnNivelFacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 220, 90));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Flecha.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 80, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Menu.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1178, 615));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNivelFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivelFacilActionPerformed
        NivelFacil nFacil = new NivelFacil();
        nFacil.setVisible(true);
    }//GEN-LAST:event_btnNivelFacilActionPerformed

    private void btnNivelIntermedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivelIntermedioActionPerformed
        NivelIntermedio nIntermedio = new NivelIntermedio();
        nIntermedio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNivelIntermedioActionPerformed

    private void btnNivelDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivelDificilActionPerformed
        NivelDificil nDificil = new NivelDificil();
        nDificil.setVisible(true);
    }//GEN-LAST:event_btnNivelDificilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNivelDificil;
    private javax.swing.JButton btnNivelFacil;
    private javax.swing.JButton btnNivelIntermedio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
